/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const Portfoliov1IndexLazyImport = createFileRoute('/portfoliov1/')()
const Portfoliov1WorkLazyImport = createFileRoute('/portfoliov1/work')()
const Portfoliov1WindowInstallationLazyImport = createFileRoute(
  '/portfoliov1/window-installation',
)()
const Portfoliov1SetdesignLazyImport = createFileRoute(
  '/portfoliov1/setdesign',
)()
const Portfoliov1AboutLazyImport = createFileRoute('/portfoliov1/about')()

// Create/Update Routes

const Portfoliov1IndexLazyRoute = Portfoliov1IndexLazyImport.update({
  path: '/portfoliov1/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/portfoliov1/index.lazy').then((d) => d.Route),
)

const Portfoliov1WorkLazyRoute = Portfoliov1WorkLazyImport.update({
  path: '/portfoliov1/work',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/portfoliov1/work.lazy').then((d) => d.Route),
)

const Portfoliov1WindowInstallationLazyRoute =
  Portfoliov1WindowInstallationLazyImport.update({
    path: '/portfoliov1/window-installation',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/portfoliov1/window-installation.lazy').then(
      (d) => d.Route,
    ),
  )

const Portfoliov1SetdesignLazyRoute = Portfoliov1SetdesignLazyImport.update({
  path: '/portfoliov1/setdesign',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/portfoliov1/setdesign.lazy').then((d) => d.Route),
)

const Portfoliov1AboutLazyRoute = Portfoliov1AboutLazyImport.update({
  path: '/portfoliov1/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/portfoliov1/about.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portfoliov1/about': {
      id: '/portfoliov1/about'
      path: '/portfoliov1/about'
      fullPath: '/portfoliov1/about'
      preLoaderRoute: typeof Portfoliov1AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/portfoliov1/setdesign': {
      id: '/portfoliov1/setdesign'
      path: '/portfoliov1/setdesign'
      fullPath: '/portfoliov1/setdesign'
      preLoaderRoute: typeof Portfoliov1SetdesignLazyImport
      parentRoute: typeof rootRoute
    }
    '/portfoliov1/window-installation': {
      id: '/portfoliov1/window-installation'
      path: '/portfoliov1/window-installation'
      fullPath: '/portfoliov1/window-installation'
      preLoaderRoute: typeof Portfoliov1WindowInstallationLazyImport
      parentRoute: typeof rootRoute
    }
    '/portfoliov1/work': {
      id: '/portfoliov1/work'
      path: '/portfoliov1/work'
      fullPath: '/portfoliov1/work'
      preLoaderRoute: typeof Portfoliov1WorkLazyImport
      parentRoute: typeof rootRoute
    }
    '/portfoliov1/': {
      id: '/portfoliov1/'
      path: '/portfoliov1'
      fullPath: '/portfoliov1'
      preLoaderRoute: typeof Portfoliov1IndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/portfoliov1/about': typeof Portfoliov1AboutLazyRoute
  '/portfoliov1/setdesign': typeof Portfoliov1SetdesignLazyRoute
  '/portfoliov1/window-installation': typeof Portfoliov1WindowInstallationLazyRoute
  '/portfoliov1/work': typeof Portfoliov1WorkLazyRoute
  '/portfoliov1': typeof Portfoliov1IndexLazyRoute
}

export interface FileRoutesByTo {
  '/portfoliov1/about': typeof Portfoliov1AboutLazyRoute
  '/portfoliov1/setdesign': typeof Portfoliov1SetdesignLazyRoute
  '/portfoliov1/window-installation': typeof Portfoliov1WindowInstallationLazyRoute
  '/portfoliov1/work': typeof Portfoliov1WorkLazyRoute
  '/portfoliov1': typeof Portfoliov1IndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/portfoliov1/about': typeof Portfoliov1AboutLazyRoute
  '/portfoliov1/setdesign': typeof Portfoliov1SetdesignLazyRoute
  '/portfoliov1/window-installation': typeof Portfoliov1WindowInstallationLazyRoute
  '/portfoliov1/work': typeof Portfoliov1WorkLazyRoute
  '/portfoliov1/': typeof Portfoliov1IndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/portfoliov1/about'
    | '/portfoliov1/setdesign'
    | '/portfoliov1/window-installation'
    | '/portfoliov1/work'
    | '/portfoliov1'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/portfoliov1/about'
    | '/portfoliov1/setdesign'
    | '/portfoliov1/window-installation'
    | '/portfoliov1/work'
    | '/portfoliov1'
  id:
    | '__root__'
    | '/portfoliov1/about'
    | '/portfoliov1/setdesign'
    | '/portfoliov1/window-installation'
    | '/portfoliov1/work'
    | '/portfoliov1/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  Portfoliov1AboutLazyRoute: typeof Portfoliov1AboutLazyRoute
  Portfoliov1SetdesignLazyRoute: typeof Portfoliov1SetdesignLazyRoute
  Portfoliov1WindowInstallationLazyRoute: typeof Portfoliov1WindowInstallationLazyRoute
  Portfoliov1WorkLazyRoute: typeof Portfoliov1WorkLazyRoute
  Portfoliov1IndexLazyRoute: typeof Portfoliov1IndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  Portfoliov1AboutLazyRoute: Portfoliov1AboutLazyRoute,
  Portfoliov1SetdesignLazyRoute: Portfoliov1SetdesignLazyRoute,
  Portfoliov1WindowInstallationLazyRoute:
    Portfoliov1WindowInstallationLazyRoute,
  Portfoliov1WorkLazyRoute: Portfoliov1WorkLazyRoute,
  Portfoliov1IndexLazyRoute: Portfoliov1IndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/portfoliov1/about",
        "/portfoliov1/setdesign",
        "/portfoliov1/window-installation",
        "/portfoliov1/work",
        "/portfoliov1/"
      ]
    },
    "/portfoliov1/about": {
      "filePath": "portfoliov1/about.lazy.tsx"
    },
    "/portfoliov1/setdesign": {
      "filePath": "portfoliov1/setdesign.lazy.tsx"
    },
    "/portfoliov1/window-installation": {
      "filePath": "portfoliov1/window-installation.lazy.tsx"
    },
    "/portfoliov1/work": {
      "filePath": "portfoliov1/work.lazy.tsx"
    },
    "/portfoliov1/": {
      "filePath": "portfoliov1/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
