/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const WorkLazyImport = createFileRoute('/work')()
const SetdesignLazyImport = createFileRoute('/setdesign')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const WorkLazyRoute = WorkLazyImport.update({
  path: '/work',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/work.lazy').then((d) => d.Route))

const SetdesignLazyRoute = SetdesignLazyImport.update({
  path: '/setdesign',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/setdesign.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/setdesign': {
      id: '/setdesign'
      path: '/setdesign'
      fullPath: '/setdesign'
      preLoaderRoute: typeof SetdesignLazyImport
      parentRoute: typeof rootRoute
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/setdesign': typeof SetdesignLazyRoute
  '/work': typeof WorkLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/setdesign': typeof SetdesignLazyRoute
  '/work': typeof WorkLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/setdesign': typeof SetdesignLazyRoute
  '/work': typeof WorkLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/setdesign' | '/work'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/setdesign' | '/work'
  id: '__root__' | '/' | '/about' | '/setdesign' | '/work'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  SetdesignLazyRoute: typeof SetdesignLazyRoute
  WorkLazyRoute: typeof WorkLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  SetdesignLazyRoute: SetdesignLazyRoute,
  WorkLazyRoute: WorkLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/setdesign",
        "/work"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/setdesign": {
      "filePath": "setdesign.lazy.tsx"
    },
    "/work": {
      "filePath": "work.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
